### ISSUE TITLE
Text ampersand replacement

### ISSUE THREAD

**Issue by amekelburg** [trustthevote/ElectionNightReportingService#2]
@alg 
The letters "And" in candidate names are getting replaced with an & in content. E.g. the presidential write-in candidates fro travis county: Rocky &Erson / Luis J. Rodriguez (should be Anderson)

**Comment by alg** [comment]
Indeed. Thanks for the catch!

**Comment by trustthevote** [comment]
Small nuance: in the correction from Mekware, please ensure the ampersand char has space on either side (in his example, its concatenated with the 2nd name, "Erson")

**Comment by alg** [comment]
I don't see where. Production version has it right at http://54.83.200.21/scoreboards/16#map/a/Federal

**Comment by johnsebes** [comment]
Looks right to me! - EJS
